source 'https://github.com/LovePlayModule/Podspec.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'LovePlay_Example' do
  pod 'LovePlay', :path => '../'
  
#  pod 'NewsList_Category', :path => '../../NewsList_Category/'
#  pod 'NewsListModule', :path => '../../NewsListModule/'
#  pod 'NewsDetailModule', :path => '../../NewsDetailModule/'
#  pod 'NewsCommentModule', :path => '../../NewsCommentModule/'

    pod 'NewsList_Category'
    pod 'NewsListModule'
    pod 'NewsDetailModule'
    pod 'NewsCommentModule'
  target 'LovePlay_Tests' do
    inherit! :search_paths

    
  end
end
